# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoLibrary
	pod 'Alamofire', '~> 4.7'
	pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '5.0.0-beta.0'
end
